name: todo
description: 'A new Flutter project.'
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  line_icons: ^2.0.1
  logger: ^1.0.0
  desktop_window: ^0.4.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.2
  provider: ^6.0.5
  intl: ^0.18.1
  table_calendar: ^3.0.9
  motion_tab_bar: ^2.0.4
  loading_animation_widget: ^1.2.0+4
  metaballs: ^1.4.2
  flutter_slidable: ^3.0.1
  math_expressions: ^2.4.0
  fl_chart: ^0.66.2
  flutter_local_notifications: ^16.3.2
  workmanager : ^0.5.2
  flutter_native_splash: ^2.3.10

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.8
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - 'lib/assets/images/'
    - 'lib/assets/audio/'
    - 'lib/assets/json/'
    - 'lib/assets/fonts/'
  fonts:
    - family: Noto_Sans_JP_Regular
      fonts:
        - asset: lib/assets/fonts/Noto_Sans_JP/static/NotoSansJP-Regular.ttf

flutter_icons:
  android: true
  ios: true
  image_path: 'lib/assets/images/logo.png'

flutter_native_splash:
  color: '#add8e6'
  background_image: 'lib/assets/images/logo.png'